name: C/C++ CI

on:
  push:
    branches: [ evopro ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build and test
      run: mkdir build && cd build && cmake .. && make && ctest --verbose
